=== GUIForWeb/Project/WebContent/WEB-INF/authentication.dtd
<!ELEMENT authentication ((auth|exception|database-error-code)+)>
<!ELEMENT auth ((category)+)>
<!ELEMENT exception ((excp)+)>
<!ELEMENT database-error-code ((error-code)+)>
<!ELEMENT category (#PCDATA)>
<!ATTLIST category name CDATA #REQUIRED>
<!ELEMENT excp (#PCDATA)>
<!ATTLIST excp name CDATA #REQUIRED>
<!ELEMENT error-code (#PCDATA)>
<!ATTLIST error-code number CDATA #REQUIRED>

=== GUIForWeb/Project/WebContent/WEB-INF/authentication.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE authentication SYSTEM "authentication.dtd">
<authentication>
	<auth>
		<category name="confirm">password</category>
		<category name="currentPassword">password</category>
	</auth>
	<exception>
		<excp name="email">admin</excp>
		<excp name="nickname">root</excp>
		<excp name="password">root</excp>
		<excp name="confirm">root</excp>
	</exception>
	<database-error-code>
		<error-code number="-1">nickname</error-code>
		<error-code number="-2">email</error-code>
		<error-code number="-3">password</error-code>
	</database-error-code>
</authentication>
